#! /bin/sh

# control windows from previous session
bspc control --adopt-orphans

# spawn panel
$HOME/.config/bspwm/panel &

# bspwm settings
bspc config border_width        3
bspc config window_gap  	6

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config normal_border_color "#073642"
bspc config active_border_color "#586e75"
bspc config focused_border_color "#cb4b16"
bspc config presel_border_color "#b58900"
bspc config urgent_border_color "#d33682"
bspc config focused_locked_border_color "#b58900"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# office setup
bspc monitor DVI-I-1 -n L
bspc monitor VGA-1 -n R
bspc monitor L -d I II III IV
bspc monitor R -d Q W E R

# rules
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^1
bspc rule -a mplayer floating=on
