#! /bin/sh
# vim:set ft=sh foldmethod=marker:

CFG_ROOT="${HOME}/.config/bspwm"
PANEL_HEIGHT=24
GAP=8

# virtual monitor
#bspc wm -a Both 3840x1080+0+0
#bspc monitor Both -d Both

# monitor setup
bspc monitor DVI-0 -n L
bspc monitor DVI-1 -n R
bspc monitor L -d I II III IV V VI
bspc monitor R -d Q W E R T Y

# misc settings
bspc config top_padding $(( ${PANEL_HEIGHT} + ${GAP} ))
bspc config border_width 3
bspc config window_gap ${GAP}
bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config click_to_focus button1

# colors
bspc config normal_border_color "#073642"
bspc config active_border_color "#586e75"
bspc config focused_border_color "#fa5000"
bspc config presel_feedback_color "#fa5000"

# rules
source ${CFG_ROOT}/rules

# panels
source ${CFG_ROOT}/panels

# autostart
source ${CFG_ROOT}/autostart

wait
