live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#75715e"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f9f8f5"
yellow = "#f4bf75"

[colors.cursor]
cursor = "#c50ed2"
text = "#ffffff"

[colors.line_indicator]
background = "#ffffff"
foreground = "#cb4b16"

[colors.normal]
black = "#272822"
blue = "#0087ff"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"

[colors.primary]
background = "#272822"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#f8f8f2"

[colors.search.focused_match]
background = "#cb4b16"
foreground = "#ffffff"

[colors.search.matches]
background = "#d1d1d1"
foreground = "#cb4b16"

[colors.vi_mode_cursor]
cursor = "#db4b16"
text = "#ffffff"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "DroidSansM Nerd Font"

[font.italic]
family = "DroidSansM Nerd Font"

[font.normal]
family = "DroidSansM Nerd Font"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"
